#!/bin/sh
### BEGIN INIT INFO
# Provides:          php5-fcgi
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the php5-cgi in fast-cgi mode
# Description:       configure and starts php5-cgi processes in fast-cgi mode using spawn-fcgi
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
SCRIPTNAME="/etc/init.d/php-fastcgi"

FCGI_PIDFILE="/var/run/spawn-php-fastcgi.pid"
FCGI_DAEMON="/usr/bin/spawn-fcgi"

USER=www-data
GROUP=www-data

FCGI_PROGRAM="/usr/bin/php-cgi"
PHP_FCGI_CHILDREN=10
PHP_FCGI_MAX_REQUESTS=1000

FCGI_PORT="9000"
FCGI_IP="127.0.0.1"

test -x $FCGI_PROGRAM || exit 0
test -x $FCGI_DAEMON || exit 0

set -e

export PHP_FCGI_CHILDREN PHP_FCGI_MAX_REQUESTS

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting spawn-fcgi"
        if ! $FCGI_DAEMON -a $FCGI_IP -p $FCGI_PORT -f $FCGI_PROGRAM -u $USER -g $GROUP -C $PHP_FCGI_CHILDREN -P $FCGI_PIDFILE; then
            log_end_msg 1
        else
            log_end_msg 0
        fi
        RETVAL=$?
  ;;
  stop)
        log_daemon_msg "Killing all spawn-fcgi processes"
        start-stop-daemon --stop --pidfile $FCGI_PIDFILE --signal 2 & log_end_msg 0 || log_end_msg 1
        RETVAL=$?
  ;;
  restart|force-reload)
        $0 stop
        $0 start
  ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 1
  ;;
esac

exit $RETVAL